### ISSUE TITLE
Add flex helper classes

### ISSUE THREAD

**Issue by baruchvlz** [mcmakler/design-guide#6]
To help ease the process of creating layouts and aligning elements, a flex helper class system might be of great use.

Example

```css
.flex{
  display: flex;
  flex: 1;
  &.justify {
    &-center {
      justify-content: center;
    }
  }
}
```

Use: `<div class="flex justify-center"></div>`
